version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
    command: --auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-import:
    container_name: mongo-import
    image: mongo:4.4.3-bionic
    command: mongoimport -u lappis -p lappis --host mongodb --db appDB --collection dados --type csv --file data/data/data_example.csv --headerline
    depends_on:
      - mongodb
    volumes:
      - .:/data

  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - 3000:3000

  app:
    build: .
    container_name: myapp
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://lappis:lappis@mongodb:27017/mydb
    depends_on:
      - mongodb
volumes:
  mongodb_data: