name: Trabalho Individual GCES Pedro Vieira

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checagem
      uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Dependencias
      run: |
        python -m venv .env
        source .env/bin/activate
        pip install -r requirements.txt
        pip install poetry
    - name: Build Docker
      working-directory: .
      run: docker-compose build app
    - name: Start Docker
      run: docker-compose up -d
    - name: Testes
      run: docker-compose run app poetry run pytest
    - name: Finalizando Container
      run: docker-compose down
    - name: Build and publish
      run: |
        poetry build
        poetry publish --username PedroV8 --password ${{ secrets.pyPIsecret }}
